# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myrunif <- function(d) {
    .Call(`_CYBERTRACK2_myrunif`, d)
}

rtmvnorm_gibbs <- function(mu, omega, init_state) {
    .Call(`_CYBERTRACK2_rtmvnorm_gibbs`, mu, omega, init_state)
}

softmax <- function(x) {
    .Call(`_CYBERTRACK2_softmax`, x)
}

weighted_colMeans <- function(Y, W, tau, L, D) {
    .Call(`_CYBERTRACK2_weighted_colMeans`, Y, W, tau, L, D)
}

weighted_colMeans_fix <- function(Y, W, premu, tau, L, D, fix_id) {
    .Call(`_CYBERTRACK2_weighted_colMeans_fix`, Y, W, premu, tau, L, D, fix_id)
}

simZ <- function(z_pre, mu, invSigma, L, w) {
    .Call(`_CYBERTRACK2_simZ`, z_pre, mu, invSigma, L, w)
}

simW <- function(Y, pi, mu, invSigma, L, minmax_id, T) {
    .Call(`_CYBERTRACK2_simW`, Y, pi, mu, invSigma, L, minmax_id, T)
}

calc_E <- function(Y, pi, mu, invSigma, L, minmax_id, T) {
    .Call(`_CYBERTRACK2_calc_E`, Y, pi, mu, invSigma, L, minmax_id, T)
}

calc_weight <- function(x, fix_id) {
    .Call(`_CYBERTRACK2_calc_weight`, x, fix_id)
}

combine_list <- function(x) {
    .Call(`_CYBERTRACK2_combine_list`, x)
}

rsample <- function(x, N, prob) {
    .Call(`_CYBERTRACK2_rsample`, x, N, prob)
}

weighted_iterative_sampling <- function(Y, L, D, Wini, xi, pi, mu, Sigma, t_id, fix_id, wis_iter) {
    .Call(`_CYBERTRACK2_weighted_iterative_sampling`, Y, L, D, Wini, xi, pi, mu, Sigma, t_id, fix_id, wis_iter)
}

pi_update <- function(W, pre_pi, minmax_id, alpha, L, T) {
    .Call(`_CYBERTRACK2_pi_update`, W, pre_pi, minmax_id, alpha, L, T)
}

alpha_update <- function(W, pre_alpha, pre_pi, L, minmax_id) {
    .Call(`_CYBERTRACK2_alpha_update`, W, pre_alpha, pre_pi, L, minmax_id)
}

sigma_update <- function(mu, Y, W, L, D, nu, tau, Lambda) {
    .Call(`_CYBERTRACK2_sigma_update`, mu, Y, W, L, D, nu, tau, Lambda)
}

sigma_update_fix <- function(mu, Y, W, preSigma, L, D, nu, tau, Lambda, fix_id) {
    .Call(`_CYBERTRACK2_sigma_update_fix`, mu, Y, W, preSigma, L, D, nu, tau, Lambda, fix_id)
}

weighted_means <- function(D, L, T, pi, t_id) {
    .Call(`_CYBERTRACK2_weighted_means`, D, L, T, pi, t_id)
}

find_popular <- function(P, all_sample_pi, fix_id, t_id) {
    .Call(`_CYBERTRACK2_find_popular`, P, all_sample_pi, fix_id, t_id)
}

fix <- function(P, all_sample_pi, pi, fix_id, t_id) {
    .Call(`_CYBERTRACK2_fix`, P, all_sample_pi, pi, fix_id, t_id)
}

stochasticEM_fix <- function(Y, L, D, Wini, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_idini, id, fix_id) {
    .Call(`_CYBERTRACK2_stochasticEM_fix`, Y, L, D, Wini, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_idini, id, fix_id)
}

stochasticEM <- function(Y, L, D, Wini, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_id) {
    .Call(`_CYBERTRACK2_stochasticEM`, Y, L, D, Wini, piini, alphaini, muini, Sigmaini, tau, nu, Lambda, num_iter, t_id)
}

cybertrack2 <- function(Y, L, D, P, Wini, piini, alphaini, muini, Sigmaini, tau, nu, xi, Lambda, num_iter, num_iter_refine, wis_iter, t_id) {
    .Call(`_CYBERTRACK2_cybertrack2`, Y, L, D, P, Wini, piini, alphaini, muini, Sigmaini, tau, nu, xi, Lambda, num_iter, num_iter_refine, wis_iter, t_id)
}

rcpparma_hello_world <- function() {
    .Call(`_CYBERTRACK2_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_CYBERTRACK2_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_CYBERTRACK2_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_CYBERTRACK2_rcpparma_bothproducts`, x)
}

